# asnity.yml
name: asnity

on:
  push:
    branches: [ test ]
  pull_request: 
    branches: [ test ]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo hihi
      - run: npm install
      - run: npm run build
      - env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - run: npm run deploy
