# asnity.yml
name: asnity

on: 
  push:
    branches:
      - test    # test 브랜치에 push가 발생했을 때
            
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        
      - name: Install Dependencies # node module install
        run: npm

      - name: Deploy 
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: 
          npm run deploy
